/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ElectroType service. Represents a row in the &quot;store_ElectroType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.service.model.impl.ElectroTypeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.service.model.impl.ElectroTypeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ElectroType
 * @generated
 */
@ProviderType
public interface ElectroTypeModel extends BaseModel<ElectroType>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a electro type model instance should use the {@link ElectroType} interface instead.
	 */

	/**
	 * Returns the primary key of this electro type.
	 *
	 * @return the primary key of this electro type
	 */
    long getPrimaryKey();

	/**
	 * Sets the primary key of this electro type.
	 *
	 * @param primaryKey the primary key of this electro type
	 */
    void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this electro type.
	 *
	 * @return the uuid of this electro type
	 */
	@AutoEscape
    String getUuid();

	/**
	 * Sets the uuid of this electro type.
	 *
	 * @param uuid the uuid of this electro type
	 */
    void setUuid(String uuid);

	/**
	 * Returns the electro type ID of this electro type.
	 *
	 * @return the electro type ID of this electro type
	 */
    long getElectroTypeId();

	/**
	 * Sets the electro type ID of this electro type.
	 *
	 * @param electroTypeId the electro type ID of this electro type
	 */
    void setElectroTypeId(long electroTypeId);

	/**
	 * Returns the name of this electro type.
	 *
	 * @return the name of this electro type
	 */
	@AutoEscape
    String getName();

	/**
	 * Sets the name of this electro type.
	 *
	 * @param name the name of this electro type
	 */
    void setName(String name);

	/**
	 * Returns the company ID of this electro type.
	 *
	 * @return the company ID of this electro type
	 */
	@Override
    long getCompanyId();

	/**
	 * Sets the company ID of this electro type.
	 *
	 * @param companyId the company ID of this electro type
	 */
	@Override
    void setCompanyId(long companyId);

}